version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - project-network

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: testdb
    networks:
      - project-network

networks:
  project-network:
    external: true
